### ISSUE TITLE
Exception when trying to save image on iOS

### ISSUE THREAD

**Issue by danieleformichelli** [kmorkos/flutter_photokit#7]
I got an exception when trying to save an image to the camera roll (similar error also when I try to save to an album).
Source code available here: https://github.com/danyf90/DFNightSelfies

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(save_asset_error, Could not save the asset, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      FlutterPhotokit.saveToCameraRoll (package:flutter_photokit/flutter_photokit.dart:34:24)
#3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#4      FlutterPhotokit.saveToCameraRoll (package:flutter_photokit/flutter_photokit.dart:30:39)
#5      _DfNightSelfiesMainState.saveMedia (package:dfnightselfies/main.dart:375:23)
#6      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#7      _DfNightSelfiesMainState.saveMedia (package:dfnightselfies/main.dart:361:19)
#8      _DfNightSelfiesMainState.getButtons.<anonymous closure> (package:dfnightselfies/main.dart:249:21)
#9      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#10     _DfNightSelfiesMainState.getButtons.<anonymous closure> (package:dfnightselfies/main.dart:247:24)
#11     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#12     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
#13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#14     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#15     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
#16     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#17     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
#18     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#20     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#21     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#22     _rootRunUnary (dart:async/zone.dart:1136:13)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#25     _invoke1 (dart:ui/hooks.dart:250:10)
#26     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)

**Comment by danieleformichelli** [comment]
Seems to be a duplicate of https://github.com/kmorkos/flutter_photokit/issues/3
